# Site settings
title: Sébastien Eustace's Blog
email: sebastien@eustace.io
description: "This blog is where I write stuff about many subjects but mainly about technology-oriented ones."
baseurl: ""
url: "http://blog.eustace.io"
twitter_username: SDisPater
github_username:  sdispater
linkedin_link: s%C3%A9bastien-eustace/79/592/697

author:
    bio: I am a Python developer with strong interests in Ruby and Go

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title.html

sass:
    sass_dir: _sass
    style: :compressed
