# Site settings
title: Sébastien Eustace's Blog
email: sebastien@eustace.io
description: "This blog is where I write stuff about many subjects but mainly about technology-oriented ones."
baseurl: ""
url: "http://blog.eustace.io"
twitter_username: SDisPater
github_username:  sdispater
linkedin_link: s%C3%A9bastien-eustace/79/592/697

author:
    bio: Born & raised in France, and currently living in the beautiful city of Quito, Ecuador, I'm a software engineer, proud pythonista (but knowledgeable in other languages and technologies as well) but overall an open source lover.

# Build settings
markdown: redcarpet
highlighter: rouge
permalink: /:title.html

sass:
    sass_dir: _sass
    style: :compressed